# Generated by Django 5.2.17 on 2026-09-30 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Matches GeoJSON', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('area_km2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('population', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Centroid for Folium', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Centroid for Folium', max_digits=9)),
            ],
            options={
                'db_table': 'districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('analyst', 'Analista'), ('viewer', 'Visualizador')], default='viewer', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('water_anomaly', 'Anomalía de agua'), ('air_quality', 'Calidad del aire'), ('incident', 'Incidencia')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Crítica'), ('warning', 'Advertencia'), ('info', 'Informativa')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'No leída'), ('acknowledged', 'Reconocida'), ('resolved', 'Resuelta')], default='unread', max_length=20)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cityFlow.district')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AirPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_at', models.DateTimeField(db_index=True)),
                ('no2_predicted', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pm10_predicted', models.DecimalField(decimal_places=2, max_digits=6)),
                ('model_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_predictions', to='cityFlow.district')),
            ],
            options={
                'db_table': 'air_predictions',
                'ordering': ['-forecast_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('in_progress', 'En progreso'), ('resolved', 'Resuelta')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='cityFlow.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='incidents', to='cityFlow.tag')),
            ],
            options={
                'db_table': 'incident_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no2_level', models.DecimalField(decimal_places=2, help_text='µg/m³', max_digits=6)),
                ('pm10_level', models.DecimalField(decimal_places=2, help_text='µg/m³', max_digits=6)),
                ('period_date', models.DateField(db_index=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_qualities', to='cityFlow.district')),
            ],
            options={
                'db_table': 'air_quality',
                'ordering': ['-period_date'],
                'unique_together': {('district', 'period_date')},
            },
        ),
        migrations.CreateModel(
            name='TourismPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hut_count', models.IntegerField(help_text='Viviendas de uso turístico (HUT)')),
                ('avg_noise_db', models.DecimalField(decimal_places=2, help_text='dB', max_digits=5)),
                ('period_date', models.DateField(db_index=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourism_pressures', to='cityFlow.district')),
            ],
            options={
                'db_table': 'tourism_pressure',
                'ordering': ['-period_date'],
                'unique_together': {('district', 'period_date')},
            },
        ),
        migrations.CreateModel(
            name='WaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_m3', models.DecimalField(decimal_places=2, max_digits=12)),
                ('domestic_consumption_m3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commercial_consumption_m3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('period_date', models.DateField(db_index=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_consumptions', to='cityFlow.district')),
            ],
            options={
                'db_table': 'water_consumption',
                'ordering': ['-period_date'],
                'unique_together': {('district', 'period_date')},
            },
        ),
        migrations.CreateModel(
            name='WaterPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(db_index=True)),
                ('expected_consumption_m3', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observed_consumption_m3', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deviation_pct', models.FloatField(help_text='% diferencia observado vs esperado')),
                ('anomaly_score', models.FloatField(help_text='0.0 a 1.0')),
                ('is_anomaly', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending_review', 'Pendiente de revisión'), ('verified_leak', 'Fuga verificada'), ('false_positive', 'Falso positivo')], default='pending_review', max_length=30)),
                ('model_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_predictions', to='cityFlow.district')),
            ],
            options={
                'db_table': 'water_predictions',
                'ordering': ['-target_date'],
                'unique_together': {('district', 'target_date')},
            },
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('temp_avg_celsius', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_max_celsius', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rainfall_mm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('humidity_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='cityFlow.district')),
            ],
            options={
                'db_table': 'weather_records',
                'ordering': ['-date'],
                'unique_together': {('district', 'date')},
            },
        ),
    ]
